services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - syntria

  db-web:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - syntria

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    env_file:
      - .env
    volumes:
      - ./api/app:/app/app
    ports:
      - "8000:8000"
    #TODO remove the following line (just for development)
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\""]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - syntria
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nicegui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - syntria

volumes:
  postgres_data:
    driver: local

networks:
  syntria:
    driver: bridge