def get_reminders():
    return [{"name": "Sms"}, {"name": "WhatsApp"}, {"name": "Telegram"}]


def get_roles():
    return [
        {"name": "Manager"},
        {"name": "Secretary"},
        {"name": "Doctor"},
        {"name": "Assistant"},
        {"name": "Emploee"},
        {"name": "Client"},
    ]


def get_categories():
    return [
        {
            "name": "Orthodontics",
            "description": "Teeth alignment and braces",
            "is_active": True,
        },
        {
            "name": "Endodontics",
            "description": "Root canal therapy and inner tooth treatments",
            "is_active": True,
        },
        {
            "name": "Periodontics",
            "description": "Prevention and treatment of gum diseases",
            "is_active": True,
        },
        {
            "name": "Prosthodontics",
            "description": "Design and fitting of artificial teeth and crowns",
            "is_active": True,
        },
        {
            "name": "Oral Surgery",
            "description": "Tooth extractions, wisdom teeth removal and surgical procedures",
            "is_active": True,
        },
        {
            "name": "Cosmetic Dentistry",
            "description": "Aesthetic treatments like veneers and teeth whitening",
            "is_active": True,
        },
        {
            "name": "Pediatric Dentistry",
            "description": "Comprehensive dental care for children and adolescents",
            "is_active": True,
        },
        {
            "name": "Preventive Dentistry",
            "description": "Routine cleanings, fluoride treatments and check-ups",
            "is_active": True,
        },
        {
            "name": "Restorative Dentistry",
            "description": "Repairing damaged teeth using fillings and bridges",
            "is_active": True,
        },
        {
            "name": "Implantology",
            "description": "Surgical placement and restoration of dental implants",
            "is_active": True,
        },
        {
            "name": "Dental Emergency",
            "description": "Urgent care for severe toothaches and dental trauma",
            "is_active": False,
        },
    ]


def get_persons(rem_map: dict):
    return [
        {
            "first_name": "Francesco",
            "last_name": "Della Casa",
            "email": "francesco@gmai.com",
            "birth_date": "2000-01-01",
            "phone_number": "3701307257",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Antonietta",
            "last_name": "Della Bella",
            "email": "antonella@email.com",
            "birth_date": "1988-02-01",
            "phone_number": "3390007257",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Matteo",
            "last_name": "Bergamaschi",
            "email": "matteo.b@gmail.com",
            "birth_date": "1992-06-15",
            "phone_number": "3471234567",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Giulia",
            "last_name": "Rossi",
            "email": "giulia.rossi@email.com",
            "birth_date": "1995-10-22",
            "phone_number": "3289876543",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Marco",
            "last_name": "Bianchi",
            "email": "mbianchi88@yahoo.it",
            "birth_date": "1988-11-05",
            "phone_number": "3334455666",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Sofia",
            "last_name": "Ricci",
            "email": "s.ricci@gmail.com",
            "birth_date": "2001-04-12",
            "phone_number": "3517654321",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Alessandro",
            "last_name": "Romano",
            "email": "alex.romano@email.com",
            "birth_date": "1979-08-30",
            "phone_number": "3398877665",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Martina",
            "last_name": "Colombo",
            "email": "marty.colombo@gmail.com",
            "birth_date": "1998-02-17",
            "phone_number": "3401122334",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Lorenzo",
            "last_name": "Ferrari",
            "email": "lorenzo.f@email.com",
            "birth_date": "1990-09-09",
            "phone_number": "3495544332",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Chiara",
            "last_name": "Esposito",
            "email": "chiara.e@yahoo.it",
            "birth_date": "1985-12-25",
            "phone_number": "3209988776",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Davide",
            "last_name": "Marino",
            "email": "davide.marino@gmail.com",
            "birth_date": "1993-03-03",
            "phone_number": "3387766554",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Sara",
            "last_name": "Russo",
            "email": "sara.russo@email.com",
            "birth_date": "2002-07-14",
            "phone_number": "3456677889",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Luca",
            "last_name": "Conti",
            "email": "luca.conti99@gmail.com",
            "birth_date": "1999-01-28",
            "phone_number": "3312233445",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Valentina",
            "last_name": "Bruno",
            "email": "vale.bruno@email.com",
            "birth_date": "1991-05-08",
            "phone_number": "3478899001",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Giuseppe",
            "last_name": "Gallo",
            "email": "ggallo@yahoo.it",
            "birth_date": "1982-11-19",
            "phone_number": "3291122334",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Elena",
            "last_name": "Costa",
            "email": "elena.costa@gmail.com",
            "birth_date": "1996-10-11",
            "phone_number": "3345566778",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Andrea",
            "last_name": "Moretti",
            "email": "a.moretti@email.com",
            "birth_date": "1994-08-14",
            "phone_number": "3351234567",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Beatrice",
            "last_name": "Barbieri",
            "email": "bea.barbieri@gmail.com",
            "birth_date": "1987-12-03",
            "phone_number": "3409876543",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Simone",
            "last_name": "Fontana",
            "email": "simone.f@yahoo.it",
            "birth_date": "1990-05-21",
            "phone_number": "3281122334",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Silvia",
            "last_name": "Rinaldi",
            "email": "silvia.rinaldi@email.com",
            "birth_date": "1999-09-09",
            "phone_number": "3475566778",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Giacomo",
            "last_name": "Lombardi",
            "email": "giacomo.lombardi@gmail.com",
            "birth_date": "1984-02-27",
            "phone_number": "3394455667",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Federica",
            "last_name": "Caruso",
            "email": "fede.caruso@email.com",
            "birth_date": "1993-11-16",
            "phone_number": "3319988776",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Stefano",
            "last_name": "Ferrara",
            "email": "s.ferrara@yahoo.it",
            "birth_date": "1981-04-08",
            "phone_number": "3456677889",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Alessia",
            "last_name": "Mariani",
            "email": "alessia.mariani@gmail.com",
            "birth_date": "2001-07-23",
            "phone_number": "3201122334",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Nicola",
            "last_name": "Bianco",
            "email": "nicola.bianco@email.com",
            "birth_date": "1989-01-11",
            "phone_number": "3385544332",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Francesca",
            "last_name": "Gatti",
            "email": "fra.gatti@gmail.com",
            "birth_date": "1997-10-30",
            "phone_number": "3498899001",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Michele",
            "last_name": "Santoro",
            "email": "michele.santoro@yahoo.it",
            "birth_date": "1975-06-15",
            "phone_number": "3341122334",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Paola",
            "last_name": "Marini",
            "email": "paola.marini@email.com",
            "birth_date": "1992-03-02",
            "phone_number": "3479988776",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Daniele",
            "last_name": "Sala",
            "email": "daniele.sala@gmail.com",
            "birth_date": "1986-09-18",
            "phone_number": "3284455667",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Laura",
            "last_name": "Fiore",
            "email": "l.fiore@email.com",
            "birth_date": "1995-12-25",
            "phone_number": "3396677889",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Roberto",
            "last_name": "De Luca",
            "email": "rob.deluca@yahoo.it",
            "birth_date": "1983-08-07",
            "phone_number": "3335566778",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Cristina",
            "last_name": "Martini",
            "email": "cristina.m@gmail.com",
            "birth_date": "2000-04-12",
            "phone_number": "3401122334",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Paolo",
            "last_name": "Galli",
            "email": "paolo.galli@email.com",
            "birth_date": "1978-01-29",
            "phone_number": "3519988776",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
        {
            "first_name": "Elisa",
            "last_name": "Coppola",
            "email": "elisa.coppola@gmail.com",
            "birth_date": "1998-11-19",
            "phone_number": "3295544332",
            "reminder_preference_id": rem_map["Telegram"],
        },
        {
            "first_name": "Enrico",
            "last_name": "Monti",
            "email": "enrico.monti@yahoo.it",
            "birth_date": "1991-05-05",
            "phone_number": "3386677889",
            "reminder_preference_id": rem_map["Sms"],
        },
        {
            "first_name": "Martina",
            "last_name": "D'Amico",
            "email": "marty.damico@email.com",
            "birth_date": "2003-02-14",
            "phone_number": "3491122334",
            "reminder_preference_id": rem_map["WhatsApp"],
        },
    ]


def get_users(roles_map: dict, p_map: dict):
    return [
        {
            "person_id": p_map["Matteo Bergamaschi"],
            "role_id": roles_map["Manager"],
            "is_active": True,
            "password": "kL9$zQ2w",
        },
        {
            "person_id": p_map["Giulia Rossi"],
            "role_id": roles_map["Assistant"],
            "is_active": True,
            "password": "pM4@vX7c",
        },
        {
            "person_id": p_map["Marco Bianchi"],
            "role_id": roles_map["Doctor"],
            "is_active": True,
            "password": "rT2#yN9b",
        },
        {
            "person_id": p_map["Sofia Ricci"],
            "role_id": roles_map["Doctor"],
            "is_active": False,
            "password": "wE8!qF3m",
        },
        {
            "person_id": p_map["Alessandro Romano"],
            "role_id": roles_map["Emploee"],
            "is_active": True,
            "password": "bV5&cH1k",
        },
        {
            "person_id": p_map["Martina Colombo"],
            "role_id": roles_map["Client"],
            "is_active": True,
            "password": "xN7*jP4d",
        },
        {
            "person_id": p_map["Lorenzo Ferrari"],
            "role_id": roles_map["Secretary"],
            "is_active": False,
            "password": "gZ3%tR8s",
        },
        {
            "person_id": p_map["Chiara Esposito"],
            "role_id": roles_map["Client"],
            "is_active": True,
            "password": "mK6^bV2n",
        },
        {
            "person_id": p_map["Davide Marino"],
            "role_id": roles_map["Client"],
            "is_active": True,
            "password": "qW1$fD5x",
        },
        {
            "person_id": p_map["Sara Russo"],
            "role_id": roles_map["Client"],
            "is_active": True,
            "password": "vC9@hJ7L",
        },
    ]


def get_items(c_map: dict):
    return [
        {
            "name": "Dental Cleaning",
            "description": "Remuval of plaque, tartar and bacteria",
            "price": 80,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Teeth Whitening",
            "description": "Professional laser bleaching",
            "price": 250,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Porcelain Veneers",
            "description": "Custom ceramic shells for front teeth",
            "price": 800,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Traditional Metal Braces",
            "description": "Full arch metal brackets",
            "price": 2500,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Clear Aligners",
            "description": "Invisible removable aligners",
            "price": 3500,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Root Canal Treatment",
            "description": "Nerve removal and sealing",
            "price": 450,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Endodontic Retreatment",
            "description": "Revision of a previous root canal",
            "price": 650,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Gum Graft Surgery",
            "description": "Tissue graft for receding gums",
            "price": 950,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Deep Scaling",
            "description": "Deep cleaning under the gumline",
            "price": 150,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Zirconia Dental Crown",
            "description": "Durable tooth-colored cap",
            "price": 650,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Full Dentures",
            "description": "Complete removable artificial teeth",
            "price": 1200,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Wisdom Tooth Extraction",
            "description": "Surgical removal of impacted 3rd molar",
            "price": 300,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Simple Tooth Extraction",
            "description": "Removal of a fully erupted tooth",
            "price": 120,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Child Routine Checkup",
            "description": "Exam and cleaning for under 12s",
            "price": 60,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Fissure Sealants",
            "description": "Protective coating for back molars",
            "price": 40,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Fluoride Application",
            "description": "Topical enamel strengthening treatment",
            "price": 35,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Composite Filling",
            "description": "Tooth-colored resin restoration",
            "price": 95,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Amalgam Filling",
            "description": "Silver alloy cavity filling",
            "price": 75,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": False,
            "is_specific": False,
        },
        {
            "name": "Single Dental Implant",
            "description": "Titanium root placement",
            "price": 1500,
            "category_id": c_map["Implantology"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Emergency Toothache Exam",
            "description": "Urgent diagnostic visit",
            "price": 50,
            "category_id": c_map["Dental Emergency"],
            "is_active": False,
            "is_specific": False,
        },
        {
            "name": "Broken Tooth Repair",
            "description": "Temporary fracture stabilization",
            "price": 150,
            "category_id": c_map["Dental Emergency"],
            "is_active": False,
            "is_specific": True,
        },
        {
            "name": "Ceramic Braces",
            "description": "Tooth-colored fixed brackets",
            "price": 2800,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Lingual Braces",
            "description": "Braces hidden behind the teeth",
            "price": 4000,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Retainer Fitting",
            "description": "Custom removable post-treatment wire",
            "price": 150,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Apicoectomy",
            "description": "Surgical removal of the tooth root tip",
            "price": 850,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Pulpotomy",
            "description": "Partial nerve removal for primary teeth",
            "price": 200,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Post and Core Build-up",
            "description": "Structural support preparation for a crown",
            "price": 300,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Crown Lengthening",
            "description": "Reshaping bone and gum tissue",
            "price": 500,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Bone Grafting",
            "description": "Jaw bone augmentation for implants",
            "price": 800,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Periodontal Maintenance",
            "description": "Specialized cleaning for gum disease patients",
            "price": 110,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Partial Denture",
            "description": "Removable replacement for several missing teeth",
            "price": 750,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Implant-Supported Bridge",
            "description": "Bridge fixed directly to surgical implants",
            "price": 2200,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Dental Flipper",
            "description": "Temporary removable partial denture",
            "price": 250,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Jaw Cyst Removal",
            "description": "Excision of cysts in the jawbone",
            "price": 900,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Alveoloplasty",
            "description": "Smoothing and shaping jawbone for dentures",
            "price": 450,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Frenectomy",
            "description": "Removal of connective tissue in the mouth",
            "price": 350,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Dental Bonding",
            "description": "Resin applied to fix chipped or cracked teeth",
            "price": 180,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Gum Contouring",
            "description": "Laser reshaping of the gum line",
            "price": 400,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Smile Makeover Consultation",
            "description": "Comprehensive aesthetic treatment evaluation",
            "price": 100,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Space Maintainer",
            "description": "Prevents teeth shifting in children",
            "price": 150,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Pediatric Pulpectomy",
            "description": "Complete root canal for baby teeth",
            "price": 250,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Stainless Steel Crown",
            "description": "Durable prefabricated cap for children's molars",
            "price": 180,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Custom Night Guard",
            "description": "Splint for bruxism and teeth grinding",
            "price": 300,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Oral Cancer Screening",
            "description": "Thorough mucosal tissue evaluation",
            "price": 50,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Panoramic X-Ray",
            "description": "Full mouth 2D diagnostic imaging",
            "price": 70,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Porcelain Inlay",
            "description": "Custom filling fitted inside tooth cusps",
            "price": 400,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Porcelain Onlay",
            "description": "Custom restoration covering one or more cusps",
            "price": 500,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Glass Ionomer Filling",
            "description": "Fluoride-releasing cavity repair material",
            "price": 80,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "All-on-4 Implants",
            "description": "Full arch replacement anchored on four screws",
            "price": 12000,
            "category_id": c_map["Implantology"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Sinus Lift",
            "description": "Adding bone to the upper jaw prior to implants",
            "price": 1100,
            "category_id": c_map["Implantology"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Tooth Reimplantation",
            "description": "Urgent stabilizing of an avulsed tooth",
            "price": 400,
            "category_id": c_map["Dental Emergency"],
            "is_active": False,
            "is_specific": True,
        },
        {
            "name": "Palatal Expander",
            "description": "Orthopedic device to widen the upper jaw",
            "price": 600,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Clear Retainer",
            "description": "Transparent post-braces alignment tray",
            "price": 200,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Orthodontic Headgear",
            "description": "Appliance for severe bite correction",
            "price": 800,
            "category_id": c_map["Orthodontics"],
            "is_active": False,
            "is_specific": True,
        },
        {
            "name": "Internal Bleaching",
            "description": "Whitening a discolored root canal tooth",
            "price": 300,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Direct Pulp Capping",
            "description": "Covering exposed nerve to avoid root canal",
            "price": 120,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Apexification",
            "description": "Inducing root closure in immature teeth",
            "price": 400,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Gingivectomy",
            "description": "Surgical removal of diseased gum tissue",
            "price": 450,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Pocket Reduction Surgery",
            "description": "Cleaning root surfaces and reducing gum pockets",
            "price": 750,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Guided Tissue Regeneration",
            "description": "Membrane placement for bone regrowth",
            "price": 850,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Maryland Bridge",
            "description": "Resin-bonded bridge attached to adjacent teeth",
            "price": 900,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Cantilever Bridge",
            "description": "Bridge supported by a single adjacent tooth",
            "price": 950,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Overdenture",
            "description": "Denture supported by implants or retained roots",
            "price": 2500,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Oral Lesion Biopsy",
            "description": "Tissue sampling for pathology analysis",
            "price": 350,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Ridge Augmentation",
            "description": "Restoring bone contour after tooth extraction",
            "price": 650,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Maxillary Antrostomy",
            "description": "Surgical access to the maxillary sinus",
            "price": 1200,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Enamel Microabrasion",
            "description": "Removal of superficial tooth stains",
            "price": 150,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Tooth Jewelry Placement",
            "description": "Bonding a small gem to the tooth surface",
            "price": 80,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": False,
            "is_specific": False,
        },
        {
            "name": "Snap-On Smile",
            "description": "Removable cosmetic arch worn over natural teeth",
            "price": 1100,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Habit Breaking Appliance",
            "description": "Device to stop thumb sucking or tongue thrusting",
            "price": 350,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Silver Diamine Fluoride",
            "description": "Liquid treatment to stop tooth decay in kids",
            "price": 60,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Pediatric Tooth Extraction",
            "description": "Removal of a loose or decayed primary tooth",
            "price": 90,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Sports Mouthguard",
            "description": "Custom-fitted athletic mouth protector",
            "price": 200,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "CBCT Scan",
            "description": "3D cone beam computed tomography imaging",
            "price": 150,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Saliva Testing",
            "description": "Diagnostic test for caries risk and dry mouth",
            "price": 75,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Gold Crown",
            "description": "Traditional highly durable metal alloy cap",
            "price": 1100,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Temporary Crown",
            "description": "Short-term acrylic cap while waiting for permanent",
            "price": 150,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Pin-Retained Restoration",
            "description": "Filling secured with metal pins for extra strength",
            "price": 250,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Mini Dental Implants",
            "description": "Narrow diameter implants for denture stabilization",
            "price": 800,
            "category_id": c_map["Implantology"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Zygomatic Implants",
            "description": "Long implants anchored directly in the cheekbone",
            "price": 3500,
            "category_id": c_map["Implantology"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Dry Socket Treatment",
            "description": "Medication dressing for post-extraction pain",
            "price": 80,
            "category_id": c_map["Dental Emergency"],
            "is_active": False,
            "is_specific": True,
        },
        {
            "name": "Interceptive Orthodontics",
            "description": "Early phase treatment for mixed dentition",
            "price": 1200,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Damon Braces",
            "description": "Self-ligating bracket system without elastics",
            "price": 3200,
            "category_id": c_map["Orthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Endodontic Surgery",
            "description": "Micro-surgical repair of complex root issues",
            "price": 950,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Vital Pulp Therapy",
            "description": "Preserving the health of the dental pulp",
            "price": 220,
            "category_id": c_map["Endodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Laser Periodontal Therapy",
            "description": "Minimally invasive laser gum treatment",
            "price": 600,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Tooth Splinting",
            "description": "Stabilizing loose teeth with wire and resin",
            "price": 250,
            "category_id": c_map["Periodontics"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Cast Partial Denture",
            "description": "Metal framework removable partial denture",
            "price": 850,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Immediate Denture",
            "description": "Denture placed immediately after extraction",
            "price": 1000,
            "category_id": c_map["Prosthodontics"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "TMJ Arthrocentesis",
            "description": "Minimally invasive jaw joint irrigation",
            "price": 700,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Orthognathic Surgery",
            "description": "Corrective jaw surgery for severe malocclusion",
            "price": 8000,
            "category_id": c_map["Oral Surgery"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Composite Veneers",
            "description": "Direct resin bonding for aesthetic improvement",
            "price": 300,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Gingival Depigmentation",
            "description": "Laser removal of dark gum pigmentation",
            "price": 450,
            "category_id": c_map["Cosmetic Dentistry"],
            "is_active": False,
            "is_specific": True,
        },
        {
            "name": "Nitrous Oxide Sedation",
            "description": "Laughing gas for pediatric and anxious patients",
            "price": 100,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Pediatric Fluoride Varnish",
            "description": "High concentration fluoride painted on teeth",
            "price": 45,
            "category_id": c_map["Pediatric Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Desensitizing Treatment",
            "description": "Application of agent for extreme tooth sensitivity",
            "price": 50,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Bitewing X-Rays",
            "description": "Routine cavity detection radiographs",
            "price": 40,
            "category_id": c_map["Preventive Dentistry"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Core Buildup",
            "description": "Structural foundation repair prior to crowning",
            "price": 200,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Inlay-Retained Bridge",
            "description": "Conservative bridge anchored by adjacent inlays",
            "price": 1800,
            "category_id": c_map["Restorative Dentistry"],
            "is_active": True,
            "is_specific": True,
        },
        {
            "name": "Implant Maintenance",
            "description": "Professional cleaning and check of dental implants",
            "price": 120,
            "category_id": c_map["Implantology"],
            "is_active": True,
            "is_specific": False,
        },
        {
            "name": "Lost Crown Recementation",
            "description": "Urgent fixing of a dislodged permanent crown",
            "price": 80,
            "category_id": c_map["Dental Emergency"],
            "is_active": True,
            "is_specific": True,
        },
    ]


def get_reservations(p_map: dict):
    return [
        {
            "reservation_date": "2026-10-02T18:29:16.671Z",
            "duration_minutes": 30,
            "description": "description",
            "patient_id": p_map["Elisa Coppola"],
            "staff_ids": [p_map["Marco Bianchi"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-03T09:00:00.000Z",
            "duration_minutes": 60,
            "description": "description",
            "patient_id": p_map["Martina Colombo"],
            "staff_ids": [p_map["Sofia Ricci"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-03T10:00:00.000Z",
            "duration_minutes": 30,
            "description": "description",
            "patient_id": p_map["Lorenzo Ferrari"],
            "staff_ids": [p_map["Marco Bianchi"]],
        },
        {
            "reservation_date": "2026-10-03T10:30:00.000Z",
            "duration_minutes": 45,
            "description": "description",
            "patient_id": p_map["Chiara Esposito"],
            "staff_ids": [p_map["Marco Bianchi"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-03T11:15:00.000Z",
            "duration_minutes": 60,
            "description": "description",
            "patient_id": p_map["Davide Marino"],
            "staff_ids": [p_map["Sofia Ricci"]],
        },
        {
            "reservation_date": "2026-10-03T14:00:00.000Z",
            "duration_minutes": 30,
            "description": "description",
            "patient_id": p_map["Sara Russo"],
            "staff_ids": [p_map["Marco Bianchi"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-04T09:30:00.000Z",
            "duration_minutes": 45,
            "description": "description",
            "patient_id": p_map["Andrea Moretti"],
            "staff_ids": [p_map["Marco Bianchi"]],
        },
        {
            "reservation_date": "2026-10-04T10:15:00.000Z",
            "duration_minutes": 90,
            "description": "description",
            "patient_id": p_map["Beatrice Barbieri"],
            "staff_ids": [p_map["Marco Bianchi"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-04T11:45:00.000Z",
            "duration_minutes": 30,
            "description": "description",
            "patient_id": p_map["Simone Fontana"],
            "staff_ids": [p_map["Marco Bianchi"]],
        },
        {
            "reservation_date": "2026-10-04T14:30:00.000Z",
            "duration_minutes": 60,
            "description": "description",
            "patient_id": p_map["Silvia Rinaldi"],
            "staff_ids": [p_map["Sofia Ricci"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-05T09:00:00.000Z",
            "duration_minutes": 30,
            "description": "description",
            "patient_id": p_map["Giacomo Lombardi"],
            "staff_ids": [p_map["Sofia Ricci"]],
        },
        {
            "reservation_date": "2026-10-05T09:30:00.000Z",
            "duration_minutes": 120,
            "description": "description",
            "patient_id": p_map["Federica Caruso"],
            "staff_ids": [p_map["Sofia Ricci"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-05T11:30:00.000Z",
            "duration_minutes": 45,
            "description": "description",
            "patient_id": p_map["Stefano Ferrara"],
            "staff_ids": [p_map["Marco Bianchi"]],
        },
        {
            "reservation_date": "2026-10-05T14:00:00.000Z",
            "duration_minutes": 60,
            "description": "description",
            "patient_id": p_map["Alessia Mariani"],
            "staff_ids": [p_map["Marco Bianchi"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-06T10:00:00.000Z",
            "duration_minutes": 30,
            "description": "description",
            "patient_id": p_map["Nicola Bianco"],
            "staff_ids": [p_map["Marco Bianchi"]],
        },
        {
            "reservation_date": "2026-10-06T10:30:00.000Z",
            "duration_minutes": 45,
            "description": "description",
            "patient_id": p_map["Francesca Gatti"],
            "staff_ids": [p_map["Sofia Ricci"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-06T11:15:00.000Z",
            "duration_minutes": 60,
            "description": "description",
            "patient_id": p_map["Michele Santoro"],
            "staff_ids": [p_map["Marco Bianchi"]],
        },
        {
            "reservation_date": "2026-10-06T14:00:00.000Z",
            "duration_minutes": 30,
            "description": "description",
            "patient_id": p_map["Paola Marini"],
            "staff_ids": [p_map["Marco Bianchi"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-07T09:00:00.000Z",
            "duration_minutes": 90,
            "description": "description",
            "patient_id": p_map["Daniele Sala"],
            "staff_ids": [p_map["Sofia Ricci"]],
        },
        {
            "reservation_date": "2026-10-07T10:30:00.000Z",
            "duration_minutes": 45,
            "description": "description",
            "patient_id": p_map["Laura Fiore"],
            "staff_ids": [p_map["Sofia Ricci"], p_map["Giulia Rossi"]],
        },
        {
            "reservation_date": "2026-10-07T11:15:00.000Z",
            "duration_minutes": 60,
            "description": "description",
            "patient_id": p_map["Elisa Coppola"],
            "staff_ids": [p_map["Sofia Ricci"]],
        },
    ]


def get_quotes(p_map: dict, i_map: dict):
    return [
        {
            "valid_until": "2026-10-02",
            "patient_id": p_map["Chiara Esposito"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Implant Maintenance"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                },
                {
                    "item_id": i_map["Inlay-Retained Bridge"],
                    "quantity": 2,
                    "discount": 0.0,
                    "teeth": [33, 16],
                },
            ],
        },
        {
            "valid_until": "2026-10-15",
            "patient_id": p_map["Martina Colombo"],
            "staff_id": p_map["Sofia Ricci"],
            "items": [
                {
                    "item_id": i_map["Teeth Whitening"],
                    "quantity": 1,
                    "discount": 10.0,
                    "teeth": [],
                }
            ],
        },
        {
            "valid_until": "2026-10-18",
            "patient_id": p_map["Davide Marino"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Dental Cleaning"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                },
                {
                    "item_id": i_map["Composite Filling"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [14],
                },
            ],
        },
        {
            "valid_until": "2026-10-20",
            "patient_id": p_map["Sara Russo"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Clear Aligners"],
                    "quantity": 1,
                    "discount": 5.0,
                    "teeth": [],
                }
            ],
        },
        {
            "valid_until": "2026-10-22",
            "patient_id": p_map["Andrea Moretti"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Root Canal Treatment"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [26],
                },
                {
                    "item_id": i_map["Zirconia Dental Crown"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [26],
                },
            ],
        },
        {
            "valid_until": "2026-10-25",
            "patient_id": p_map["Beatrice Barbieri"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Panoramic X-Ray"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                },
                {
                    "item_id": i_map["Simple Tooth Extraction"],
                    "quantity": 2,
                    "discount": 0.0,
                    "teeth": [38, 48],
                },
            ],
        },
        {
            "valid_until": "2026-10-28",
            "patient_id": p_map["Simone Fontana"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Single Dental Implant"],
                    "quantity": 1,
                    "discount": 15.0,
                    "teeth": [46],
                }
            ],
        },
        {
            "valid_until": "2026-11-02",
            "patient_id": p_map["Silvia Rinaldi"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Porcelain Veneers"],
                    "quantity": 4,
                    "discount": 20.0,
                    "teeth": [11, 12, 21, 22],
                }
            ],
        },
        {
            "valid_until": "2026-11-05",
            "patient_id": p_map["Giacomo Lombardi"],
            "staff_id": p_map["Sofia Ricci"],
            "items": [
                {
                    "item_id": i_map["Full Dentures"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                }
            ],
        },
        {
            "valid_until": "2026-11-10",
            "patient_id": p_map["Federica Caruso"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Dental Cleaning"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                },
                {
                    "item_id": i_map["Composite Filling"],
                    "quantity": 2,
                    "discount": 0.0,
                    "teeth": [15, 25],
                },
            ],
        },
        {
            "valid_until": "2026-11-12",
            "patient_id": p_map["Stefano Ferrara"],
            "staff_id": p_map["Sofia Ricci"],
            "items": [
                {
                    "item_id": i_map["Deep Scaling"],
                    "quantity": 1,
                    "discount": 10.0,
                    "teeth": [],
                }
            ],
        },
        {
            "valid_until": "2026-11-15",
            "patient_id": p_map["Alessia Mariani"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Traditional Metal Braces"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                }
            ],
        },
        {
            "valid_until": "2026-11-18",
            "patient_id": p_map["Nicola Bianco"],
            "staff_id": p_map["Sofia Ricci"],
            "items": [
                {
                    "item_id": i_map["Ceramic Braces"],
                    "quantity": 1,
                    "discount": 5.0,
                    "teeth": [],
                }
            ],
        },
        {
            "valid_until": "2026-11-20",
            "patient_id": p_map["Francesca Gatti"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Panoramic X-Ray"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                },
                {
                    "item_id": i_map["Wisdom Tooth Extraction"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [28],
                },
            ],
        },
        {
            "valid_until": "2026-11-25",
            "patient_id": p_map["Michele Santoro"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Gum Graft Surgery"],
                    "quantity": 1,
                    "discount": 10.0,
                    "teeth": [41, 42],
                }
            ],
        },
        {
            "valid_until": "2026-11-28",
            "patient_id": p_map["Paola Marini"],
            "staff_id": p_map["Sofia Ricci"],
            "items": [
                {
                    "item_id": i_map["Dental Bonding"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [11],
                }
            ],
        },
        {
            "valid_until": "2026-12-02",
            "patient_id": p_map["Daniele Sala"],
            "staff_id": p_map["Sofia Ricci"],
            "items": [
                {
                    "item_id": i_map["Custom Night Guard"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                }
            ],
        },
        {
            "valid_until": "2026-12-05",
            "patient_id": p_map["Laura Fiore"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Apicoectomy"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [22],
                }
            ],
        },
        {
            "valid_until": "2026-12-10",
            "patient_id": p_map["Elisa Coppola"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Dental Cleaning"],
                    "quantity": 1,
                    "discount": 5.0,
                    "teeth": [],
                },
                {
                    "item_id": i_map["Fluoride Application"],
                    "quantity": 1,
                    "discount": 5.0,
                    "teeth": [],
                },
            ],
        },
        {
            "valid_until": "2026-12-15",
            "patient_id": p_map["Paolo Galli"],
            "staff_id": p_map["Sofia Ricci"],
            "items": [
                {
                    "item_id": i_map["Bone Grafting"],
                    "quantity": 1,
                    "discount": 15.0,
                    "teeth": [36],
                },
                {
                    "item_id": i_map["Single Dental Implant"],
                    "quantity": 1,
                    "discount": 15.0,
                    "teeth": [36],
                },
            ],
        },
        {
            "valid_until": "2026-12-20",
            "patient_id": p_map["Martina D'Amico"],
            "staff_id": p_map["Marco Bianchi"],
            "items": [
                {
                    "item_id": i_map["Teeth Whitening"],
                    "quantity": 1,
                    "discount": 0.0,
                    "teeth": [],
                }
            ],
        },
    ]
